name: workflow_verification     

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:

jobs:
  build:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      
      # Clone le repo
      - uses: actions/checkout@v4

      # Install Node.js
      - uses: actions/setup-node@v4

      # Install les dependances precisé
      - run: npm ci

      # Télécharge Eslint
      - uses: eslint/github-action@v4.0.1
    