name:
  workflow_verification

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm
    - name: Install Eslint via yarn 
      run: npm add eslint --dev 
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx